alumnium-hq/alumnium

alumnium/alumni.py
examples/pytest/google_test.py
poetry.lock
pyproject.toml

The retry serves as a simplistic manager agent. In a situation when the model attempts to do too much on the page. For example, in Google search it's common to for model to suggest to type word in the search box, press Enter and then click "Search" button. The last step is redundant and causes the test to fail. Retry would attempt to search again and the model would respond that nothing needs to be done since the goal is achieved.
Eventually, we want to replace retry with a more intelligent agent that would constantly evaluate what needs to be done to achieve the goal as the action is executed.
This reverts commits e1b734d, 961d35a and bb6b59d.

revert: retry actions

---

alumnium/agents/__init__.py
alumnium/agents/loading_detector_agent.py
alumnium/agents/loading_detector_prompts/system.md
alumnium/agents/loading_detector_prompts/user.md
alumnium/agents/verifier_agent.py
examples/pytest/retry_test.py

This is a basic retry implementation that catches verification errors and checks whether the page is loading. If it does, it would wait 0.5s and retry up to 5s.
VerifierAgent should not really know about LoadingDetectorAgent, a high-level abstraction is needed here (e.g. CoordinatorAgent). It's worth to add it later when we need to add retries for ActorAgent too.

feat: retry verification if page is loading

---

.github/workflows/ci.yml
alumnium/agents/__init__.py
alumnium/agents/contradiction_checker_agent.py
alumnium/agents/contradiction_checker_prompts/user.md
alumnium/agents/verifier_agent.py
alumnium/alumni.py
examples/behave/features/todo.feature
examples/pytest/drag_and_drop_test.py

Sometimes LLMs would incorrectly fail the verfication and provide an explanation that contradicts itself. For example, given the following verification "square A is positioned to the left of square B", LLM sometimes fails it but provide weird explanation: "The visual representation shows square A to the right of square B, indicating that square B is not positioned to the left of square A."
This commit compensates for such behavior by double-checking the verification explanation for contradictions.

feat: check verification result for contradictions

---

.github/workflows/ci.yml
alumnium/agents/actor_agent.py
alumnium/alumni.py
alumnium/models.py
examples/pytest/calculator_test.py
examples/pytest/drag_and_drop_test.py

This is initial support for Llama 3.2 90B vision instruct model!
For such a big model, it's very hard to make it work locally with all Alumnium requirements (tool calling, structured output, multimodal). For the time being, AWS Bedrock is a provider that proves to work fine in this initial implementation.
There are few things to keep in mind in this initial implementation:
1. tool calling types are less strict (e.g. it's common for the model to return str instead of int/bool). Pydantic coercion helps with this.
2. vision is disabled for now - when the model is used both with image and structured output, the latter does not work. This can probably be worked around with custom response parsing, but this is left for the future (maybe AWS will fix it eventually).
3. images needs to be resized …

feat: llama-3.2 on bedrock

---

alumnium/drivers/selenium_driver.py

This is a workaround for https://github.com/SeleniumHQ/selenium/issues/14799, though we would still need to support the older Selenium versions so it will stick around at least until Selenium 5.
Fixes #11.

feat: support remote chromium drivers

---

.github/workflows/ci.yml

This simplifies release automation by removing the need to create a tag and run two CI workflows - one for commit and one for the tag.
Instead, simply bump the version in `pyproject.toml` and commit with a message starting with `release:`. The CI workflow will read a version from `pyproject.toml`, build a package, and create a release and a tag on GitHub.

ci: create release/tag on `release:` commit

---

.github/workflows/ci.yml
alumnium/agents/actor_agent.py
alumnium/agents/contradiction_checker_agent.py
alumnium/agents/loading_detector_agent.py
alumnium/agents/verifier_agent.py
alumnium/delayed_runnable.py
examples/pytest/calculator_test.py

This addition allows delaying requests to the LLM. This can be useful when using free tiers of AI providers. For example, Google AI Studio has a free plan for Gemini limited to 15 requests per minute. It's possible to set `ALUMINIUM_RPM_LIMIT=15`, which will delay every request by 4 seconds, ensuring the tests don't encounter a "429 Resource Exhausted" error.

feat: rate limit requests

---

alumnium/agents/retriever_agent.py
alumnium/agents/retriever_prompts/system.md
alumnium/drivers/playwright_driver.py
examples/pytest/table_test.py

This commit ensures that retriever only uses the context to extract data and not try to look the answer up using its own knowledge.

fix: prevent retriever from guessing answer

---

.tool-versions
alumnium/agents/retriever_agent.py

Looks like double-quotes are not allowed in f-strings surrounded by double-quotes on Python 3.10.
```
>>> import alumnium
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/p0deje/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/alumnium/__init__.py", line 17, in <module>
from .alumni import *
File "/Users/p0deje/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/alumnium/alumni.py", line 12, in <module>
from .agents import *
File "/Users/p0deje/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/alumnium/agents/__init__.py", line 3, in <module>
from .retriever_agent import RetrieverAgent
File "/Users/p0deje/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/alumnium/agents/retriever_agent.py", line 86
logger.info(f"  <- …
```

fix: syntax error on f-string

---

.tool-versions
Makefile
alumnium/agents/actor_agent.py
alumnium/agents/planner_agent.py
alumnium/agents/retriever_agent.py
alumnium/aria.py
alumnium/drivers/playwright_driver.py
alumnium/drivers/selenium_driver.py
examples/behave/features/steps/todo_al.py
examples/pytest/table_test.py
poetry.lock
pyproject.toml

This PR adds the Flake8 linter to the project and fixes (or ignores) all violations it reports.
https://flake8.pycqa.org
Flake8 is a pretty standard tool for checking code style in Python. It is a combination linter that runs checks using the `mccabe`, `pyflakes`, and `pycodestyle` tools. It is not an autoformatter like `black`... it just displays violations that need to be fixed manually. It finds many style issues that `black` doesn't care about.
Changes in this PR:
- Added `flake8` and `flake8-pyproject` dev dependencies to `pyproject.toml`. (`flake8-pyproject` is needed to read Flake8 configuration from `pyproject.toml`)
- Generated new `poetry.lock` file to include the new dependencies.
- Added `flake8` to the `format` task in `Makefile` (configured to scan the entire codebase, …

Add flake8 linting and cleanup violations

---

Makefile
pyproject.toml
tests/test_aria.py
tests/test_llm_response.py

This PR fixes code formatting after linting violations were introduced in #63.
It also:
- adds the `tests` directory to `flake8` in the `format` target of `Makefile` (to catch future violations)
- adds duplicate key detection to the `autoflake` configuration.

Fix code formatting

---

.github/workflows/ci.yml
CODE_OF_CONDUCT.md

There is a minor spelling issue in `CI.yml` file after #64  merge , because of this CI got failed .  Extra 'S' character being added to `.tool-versions` attribute in new Code Style Check job , because of this CI failed . Sorry for this , Fixed now .

CI :  Removed extra character 's' from .tool-version attribute 

---

.github/ISSUE_TEMPLATE/Issue.yml

-  Added `Mistral-small 3.1 24B(Ollama)` in Issue template form as per `0.9.0` release .
-  Added new field named `label : Bug` in Issue.yml .
-  Modified title field to `title: [Bug]` .

Added mistral small in LLM version of Issue template

---

alumnium/logutils.py

- adds a fallback default for `ALUMNIUM_LOG_PATH` env variable
- fixes `ALUMNIUM_LOG_LEVEL` env variable configuration

fix: environment variable setup for logutils

---

.github/ISSUE_TEMPLATE/Issue.yml

- removed `label `key from CI.yml . This is unnecessarily causing errors in `Issue_template` form  .
- I have removed it in the` pre-commit ` branch in #79  but still it is getting displayed .
- @sh3pik  , Thanks for pointing it in that PR , I have it removed it and committed in pre-commit branch. but not sure how again it got added again . Sorry for the inconvenience.

fix: removed label key from ci.yml

---

.github/workflows/ci.yml

The current CI setup doesn't allow running tests on PRs from forks because the secrets are not available. The suggested workaround is to extract the test execution into a callable workflow, which has access to secrets. Then, when the PR is opened and one of the maintainers approves workflow execution, it would be able to run the tests without any issues.
There is a security risk that something in PR could steal tokens (e.g. dependency in poetry.lock) so extra attention from maintainers is required. At this point, since all AI providers are capped with a small budget, the overall risk is negligible.
@sh3pik I cannot test this before merging, so please just see if the solution makes sense.

ci: run tests on PRs from forks

---

alumnium/alumni.py
alumnium/models.py

- As per #93 , @p0deje  mentioned in comments , that we are going to support users with flexible models provided in the following format  `export ALUMNIUM_MODEL="<provider>/<model>"` .
- have designed two new methods in models.py file named `Model.provider` returns `enum `and `Model.name` which returns the `string ` value of the provider .
- in `alumni.py` , replaced the existing variable` self.model` with `self.provider`  and created a new variable `self.name` .
- for eg: if user sets `ALUMNIUM_MODEL `as "`google/gemini-2.0-flash-lite`" , in `self.model` `google `value is stored and in `self.provider` `gemini-2.0-flash-lite` is stored and passed to constructor , as a fallback implementation if user sets google only then the default model is being taken from `models.py`.

feat: support custom LLM invocation

---

alumnium/agents/actor_agent.py
alumnium/drivers/appium_driver.py
alumnium/tools/__init__.py

Implements idiomatic method for restricting use of unavailable tools based on current driver
- In this PR, specifically ```hover``` in Appium
Possible solution for for stress-free removal of methods from drivers
Please verify the following before submitting:
- A possible solution

Prevent ActorAgent from Invoking Tools that Aren't Implemented/Available

---

alumnium/llm_factory.py
alumnium/tools/back_tool.py
examples/pytest/navigation_test.py

Fixes #157  
- If user sets `ALUMNIUM_OLLAMA_URL` environment variable value , in `llm_factory.py` class for `ChatOllama` constructor in place of `base_url` parameter we are passing the value .

feat : support ollama config url 

---

.claude/settings.local.json
alumnium/__init__.py
alumnium/alumni.py
alumnium/area.py
alumnium/cache.py
alumnium/clients/http_client.py
alumnium/clients/native_client.py
alumnium/server/README.md
alumnium/server/api_models.py
alumnium/server/main.py
examples/behave/features/environment.py
examples/pytest/conftest.py
tests/server/test_server.py

Introduce a new HTTP client that can be used to drive the Python package using the Alumnium server. It is enabled when `url` parameter is passed to `Alumni()`. It's functionally the same as a native client.
Part of a larger #105 work.
<details>
<summary>Checked by running all the tests with an HTTP client against the server.</summary>
```sh
$ make start-server
poetry run alumnium-server
INFO:     Will watch for changes in these directories: ['/Users/p0deje/Development/alumnium']
INFO:     Uvicorn running on http://0.0.0.0:8013 (Press CTRL+C to quit)
INFO:     Started reloader process [6631] using WatchFiles
INFO:     Started server process [6661]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:63217 - "POST /v1/sessions HTTP/1.1" 200 …
```

feat: http client
