alumnium-hq/alumnium

examples/behave/features/steps/todo_al.py, examples/behave/features/steps/todo_webdriver.py, examples/behave/features/todo.feature
The latter sometimes confuses LLM as it considers it to be the future state rather that the present.
=> test: use `is` instead of `should be`

README.md
https://github.com/alumnium-hq/alumnium.github.io/pull/8
=> docs: move to alumnium.ai

.github/workflows/ci.yml, alumnium/agents/__init__.py, alumnium/agents/confirmation_checker_agent.py, alumnium/agents/confirmation_checker_prompts/user.md, alumnium/agents/contradiction_checker_prompts/user.md, alumnium/agents/verifier_agent.py, alumnium/agents/verifier_prompts/_user_text.md, alumnium/agents/verifier_prompts/user.md, alumnium/alumni.py, alumnium/drivers/selenium_driver.py, alumnium/tools/select_tool.py, examples/behave/features/steps/todo_al.py, examples/pytest/calculator_test.py, examples/pytest/drag_and_drop_test.py, examples/pytest/select_test.py
Please see individual commits for details.
=> Multiple fixes and improvements

scripts/waiter.js
- lazy loading resources are only loaded when on the screen, so the script skips waiting for them now
- added the debugging option to easy debugging in the future
=> fix: exclude loading="lazy" resources from waiting for

.github/workflows/ci.yml, examples/pytest/conftest.py
DuckDuckGo fails when using headless
=> ci: run headful playwright

CONTRIBUTING.md
This pull request adds a CONTRIBUTING.md file to help guide new contributors who want to support the Aluminium project.
The document is written in a friendly and human tone that reflects the spirit of open collaboration. It outlines contribution steps clearly, from forking the repo to creating a pull request, while also encouraging new contributors to ask questions and learn along the way.
=> Created Proposal for CONTRIBUTING.md

README.md
=> #48 update ReadMe

.gitignore, alumnium/alumni.py, examples/pytest/conftest.py, tests/test_aria.py, tests/test_llm_response.py
#42, added unit tests for LLMs
=> Added testcase for llm and ariaTree

.github/workflows/ci.yml, Makefile, pyproject.toml
1. Remove unnecessary grouping in poetry.
2. Add venv cache on CI.
3. Ensure flake8 picks up new folders.
=> chore: improve format checking

alumnium/agents/actor_agent.py, alumnium/agents/actor_prompts/anthropic/system.md, alumnium/agents/actor_prompts/anthropic/user.md, alumnium/agents/actor_prompts/deepseek/system.md, alumnium/agents/actor_prompts/deepseek/user.md, alumnium/agents/actor_prompts/google/system.md, alumnium/agents/actor_prompts/google/user.md, alumnium/agents/actor_prompts/openai/system.md, alumnium/agents/actor_prompts/openai/user.md
Implements Task #61: Introduce per-model prompts.
This PR proposes a solution for implementing per-model prompts as discussed in issue #61.
I'd appreciate your feedback on the approach I've taken. Please let me know if you see any alternative solutions or areas for improvement.
I will update the prompts for each model if the approach looks good
=> [Draft] feat(#61)| Introduce per-model prompts

alumnium/__init__.py, alumnium/agents/actor_agent.py, alumnium/agents/planner_agent.py, alumnium/agents/retriever_agent.py, alumnium/alumni.py, alumnium/aria.py, alumnium/cache.py, alumnium/drivers/playwright_driver.py, alumnium/drivers/selenium_driver.py, alumnium/logutils.py
Refactored `logutils`:
- initialise the logger only once in `__init__.py`
- do not invoke `basicConfig()` multiple times
- prevent race condition when writing to the file
=> Chore: refactor logger

alumnium/accessibility/xcuitest_accessibility_tree.py, alumnium/agents/actor_agent.py, tests/accessibility/test_xcuitest_accessibilty_tree.py
- reactors XCUITestAccessibilityTree
- cache node elements in `cache_ids`
- adds Node dataclass
- adds debug logging of accessibility tree
=> chore: refactor XCUITestAccessibilityTree

.github/workflows/ci.yml, alumnium/drivers/appium_driver.py, examples/pytest/conftest.py
- Adds an appium driver example to the pytest examples' conftest.py (most recent ios)
- Adds url property  functionality for AppiumDriver
Useful for appium development
Continues #113 
Mark the relevant options.
To run the appium server for testing
```bash
appium --address 127.0.0.1 --port 4724 --base-path /wd/hub --log-level info
```
passed calculator local test:
```bash
============================= test session starts ==============================
platform darwin -- Python 3.11.5, pytest-8.3.4, pluggy-1.5.0
rootdir: /Users/simonbenzer/Desktop/Repos/Github/alumnium
configfile: pyproject.toml
plugins: html-4.1.1, metadata-3.1.1, retry-1.7.0, anyio-4.8.0
collected 1 item                                                               
examples/pytest/calculator_test.py . …
```
=> Added Appium example to conftest.py and built out AppiumDriver's url property

alumnium/drivers/appium_driver.py, examples/pytest/calculator_test.py, examples/pytest/conftest.py, examples/pytest/drag_and_drop_test.py, examples/pytest/search_test.py, examples/pytest/select_test.py, examples/pytest/swag_labs_test.py, examples/pytest/table_test.py, examples/pytest/waiting_test.py
=> feat: appium title extraction

examples/pytest/bstackdemo_test.py
One more example that I have shown in https://youtu.be/NbQrcpllTyA
=> test: add bstackdemo example

.github/workflows/ci.yml
Store Alumnium cache on CI to improve stability and performance: https://alumnium.ai/docs/guides/caching/
=> ci: save cache file

alumnium/agents/actor_agent.py, alumnium/agents/area_agent.py, alumnium/agents/planner_agent.py, alumnium/agents/retriever_agent.py, alumnium/alumni.py, alumnium/area.py, alumnium/tools/__init__.py, alumnium/tools/base_tool.py, alumnium/tools/click_tool.py, alumnium/tools/drag_and_drop_tool.py, alumnium/tools/hover_tool.py, alumnium/tools/press_key_tool.py, alumnium/tools/select_tool.py, alumnium/tools/type_tool.py, examples/pytest/table_test.py
It's the first step in having a client-server architecture.
Refactored the code to make agents work with the provided data instead of calling the driver's methods.
Part of issue https://github.com/alumnium-hq/alumnium/issues/105
=> feat: separate LLM agents and web/mobile drivers

alumnium/agents/actor_prompts/mistralai/system.md, alumnium/agents/actor_prompts/mistralai/user.md, alumnium/agents/area_prompts/mistralai/system.md, alumnium/agents/area_prompts/mistralai/user.md, alumnium/agents/base_agent.py, alumnium/agents/planner_agent.py, alumnium/agents/planner_prompts/mistralai/system.md, alumnium/agents/planner_prompts/mistralai/user.md, alumnium/agents/retriever_prompts/mistralai/_user_text.md, alumnium/agents/retriever_prompts/mistralai/system.md, examples/pytest/table_test.py
Enables structured planner on MistralAI models similar to #135, #142, and #144.
=> feat!: structured planner on mistralai

alumnium/agents/planner_agent.py, alumnium/agents/retriever_agent.py
Using arrows seems to produce more stable results on most newer models.
=> feat: change separator

alumnium/cache.py
Use a timeout to wait for the database lock to be released and explicitly roll back the transaction if it fails. There are likely more issues around parallelism, but it's a good start.
Fixes #115.
=> fix(cache): better handle of parallel cache access

alumnium/agents/planner_prompts/deepseek/system.md, alumnium/agents/planner_prompts/google/system.md, alumnium/agents/planner_prompts/meta/system.md, alumnium/agents/planner_prompts/mistralai/system.md, alumnium/agents/planner_prompts/openai/system.md, alumnium/drivers/appium_driver.py, alumnium/drivers/base_driver.py, alumnium/drivers/playwright_driver.py, alumnium/drivers/selenium_driver.py, alumnium/tools/__init__.py, alumnium/tools/back_tool.py, examples/behave/features/environment.py, examples/pytest/conftest.py, examples/pytest/navigation_test.py
This PR introduces a new tool into the framework which is helping user navigate back during testing.
I introduced this update because I needed it on my personal project and I though it might be useful for other people too.
No related issues.
Mark the relevant options.
I added another test that if validating this.
Please verify the following before submitting:
=> feat(tool): add "Go Back"

.github/workflows/ci.yml, .gitignore, alumnium/agents/retriever_agent.py, alumnium/alumni.py, alumnium/area.py, alumnium/cache/filesystem_cache.py, alumnium/cache/null_cache.py, alumnium/cache/sqlite_cache.py, alumnium/cache_factory.py, alumnium/fscache.py, alumnium/session.py, examples/behave/features/environment.py, examples/pytest/bstackdemo_test.py, examples/pytest/conftest.py, examples/pytest/navigation_test.py, examples/pytest/swag_labs_test.py
This pull request introduces a new flexible caching architecture for Alumnium, adds a filesystem-based cache, and updates the retriever agent API for improved integration and test reporting. The changes include refactoring the cache system to support multiple backends (filesystem, SQLite, or none), updating the retriever agent and its consumers to return structured data, and enhancing test output to include detailed cache usage. There are also minor updates to test configurations and platform versions. Cache backend is controlled by `ALUMNIUM_CACHE` variable, which can be either `filesystem`, `sqlite` or `false`.
=> feat!: filesystem cache

alumnium/server/README.md, alumnium/server/api_models.py, alumnium/server/main.py, alumnium/server/tests/test_server.py
The PR updates the server API to comply with the RESTful approach.
Mark the relevant options.
=> feat: add v1 prefix and format to RESTful rules

.dockerignore, .github/workflows/release.yml, .gitignore, Dockerfile, Makefile, alumnium/server/README.md
Packages the server into a Docker image and publishes to https://hub.docker.com/r/alumnium/alumnium. This image is going to be used by clients implemented in other languages.
See #105 for more details.
The docker image can be run as following:
```sh
docker run --rm -p 8013:8013 \
-v $(PWD)/.alumnium/cache:/app/.alumnium/cache \
--env-file .env \
-e ALUMNIUM_CACHE \
-e ALUMNIUM_LOG_PATH=stdout \
-e ALUMNIUM_OLLAMA_URL \
alumnium/alumnium
```
Once started, you can use the server to create a session:
```sh
curl -X POST http://localhost:8013/v1/sessions \
-H "Content-Type: application/json" \
-d '{
"provider": "azure_openai",
"tools": [
{
"type": "function",
"function": {
"name": "ClickTool",
"description": "Click an element.",
"parameters": {
"type": "object",
"properties": {
"id": {"type": …
```
=> feat: docker image for server
